In [1]:
import sys
sys.path.append("/Users/danielmunson/dev/simple_net")

from pprint import pprint

In [2]:
import numpy as np

from simple_net.components.network import Network
from simple_net.functions.utils import vectorize
from simple_net.functions.cost import (
    mean_squared_error,
    mse_gradient,
    arithmetic_mean
)
from simple_net.functions.activations import (
    sigmoid, ddx_sigmoid
)

In [3]:
test_features, test_answers = zip(*[
    (np.random.rand(50), np.random.rand(10)) for i in range(20)
])

In [4]:
layers = [50, 30, 10]
NN = Network(
    layer_dims = layers,
    activations = [sigmoid for _ in layers],
    activation_derivatives = [ddx_sigmoid for _ in layers],
    cost_function = mean_squared_error,
    cost_gradient = mse_gradient,
    learning_rate = 5,
    gradient_aggregator = arithmetic_mean
)

In [5]:
for layer in NN._layers:
    pprint(layer._bias)

array([-0.32244909,  0.77972358, -1.14418386, -0.3218481 ,  0.03610794,
       -1.76658312,  0.68030744, -1.2657485 ,  1.71617365,  0.15433448,
        0.10355731,  2.09235789, -0.24976951,  1.93824961,  2.18853154,
       -0.15224834,  0.30266864,  0.30906514,  0.32070375,  0.79705328,
       -0.70272505, -0.40341493,  0.88691449, -0.21133998, -1.00945083,
       -1.07886014,  0.56723692, -0.33086629,  2.35314633, -1.6524033 ])
array([-0.67581468,  0.06537781, -0.42427549, -1.303061  , -0.26634136,
        0.24318272,  0.22746583,  0.29992697, -0.61692591, -0.50336644])


In [6]:
NN.run_epoch(test_features[:5], test_answers[:5])

[ 1.13939618e-02  1.74185155e-02 -2.88823824e-01  3.14942686e-01
 -5.55037270e-02 -1.56581772e-02 -9.74779326e-03  1.29696950e-01
  3.11777874e-04  3.87985402e-01]
[-5.16721726e-02 -2.25292725e-02  1.76318322e-02  9.22548627e-06
  6.05929427e-02  1.18095029e-02  1.38581851e-04  1.56999073e-03
  8.18274468e-03 -2.24204846e-02  8.98579519e-02  2.57836292e-02
 -2.91966065e-02  5.42035164e-04 -1.54717367e-02  5.66624790e-02
  4.91919182e-05  6.59594321e-02 -4.68356589e-02  1.82961797e-01
 -2.39806923e-01 -1.43213313e-03 -1.38892218e-02  6.88910164e-02
  1.10712448e-01  2.37137708e-03  3.55547305e-03 -2.63212516e-02
 -1.21652857e-02 -2.86495370e-02]


In [7]:
for layer in NN._layers:
    pprint(layer._bias)

pprint(NN._epochs)

array([-0.37412126,  0.75719431, -1.12655203, -0.32183887,  0.09670088,
       -1.75477362,  0.68044602, -1.26417851,  1.7243564 ,  0.131914  ,
        0.19341526,  2.11814152, -0.27896611,  1.93879164,  2.1730598 ,
       -0.09558586,  0.30271783,  0.37502457,  0.2738681 ,  0.98001508,
       -0.94253197, -0.40484707,  0.87302527, -0.14244897, -0.89873838,
       -1.07648876,  0.57079239, -0.35718754,  2.34098104, -1.68105284])
array([-0.66442072,  0.08279633, -0.71309931, -0.98811831, -0.32184509,
        0.22752454,  0.21771803,  0.42962392, -0.61661413, -0.11538104])
[{'aggregate_gradient': array([-0.39562149, -0.69905791,  0.26221634, -0.43229759,  0.42281006,
        0.43129333,  0.03475647, -0.24963921, -0.61605107, -0.33944481]),
  'cost_values': (1.861476559305234,
                  2.864350654830183,
                  3.568031993355209,
                  2.912855940624229,
                  2.4642316840852585),
  'gradients': (array([ 0.02509675, -0.9205565 , -0.26355017, -0.